// env.example.js
// Copy to env.js locally for dev. In GitHub Pages, env.js is generated by the workflow.
window.__FIREBASE_CONFIG = {
  apiKey: "YOUR_API_KEY",
  authDomain: "your-app.firebaseapp.com",
  projectId: "your-app",
  storageBucket: "your-app.appspot.com",
  messagingSenderId: "1234567890",
  appId: "1:1234567890:web:abc123",
  measurementId: "G-XXXXXXX"
};

// Optional: if you enable App Check (recommended)
window.__RECAPTCHA_V3_SITE_KEY = ""; // e.g., "6Lc...your_site_key"
